branch-defaults:
  default:
    environment: music-website-env
    group_suffix: null
  master:
    environment: music-website-dev
global:
  application_name: music-website
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
